//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraversalProjeCore.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _MemberLayout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _MemberLayout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraversalProjeCore.Resources.Views.Shared._MemberLayout", typeof(_MemberLayout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktif Rez.
        /// </summary>
        public static string Aktif_Rez {
            get {
                return ResourceManager.GetString("Aktif Rez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string Çıkış_Yap {
            get {
                return ResourceManager.GetString("Çıkış Yap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçmiş Rez.
        /// </summary>
        public static string Geçmiş_Rez {
            get {
                return ResourceManager.GetString("Geçmiş Rez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay Bekleyen Rez.
        /// </summary>
        public static string Onay_Bekleyen_Rez {
            get {
                return ResourceManager.GetString("Onay Bekleyen Rez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilim.
        /// </summary>
        public static string Profilim {
            get {
                return ResourceManager.GetString("Profilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siteye Git.
        /// </summary>
        public static string Siteye_Git {
            get {
                return ResourceManager.GetString("Siteye Git", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Rotalar.
        /// </summary>
        public static string Son_Rotalar {
            get {
                return ResourceManager.GetString("Son Rotalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tur Rotaları.
        /// </summary>
        public static string Tur_Rotaları {
            get {
                return ResourceManager.GetString("Tur Rotaları", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni Rezervasyon.
        /// </summary>
        public static string Yeni_Rezervasyon {
            get {
                return ResourceManager.GetString("Yeni Rezervasyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlarım.
        /// </summary>
        public static string Yorumlarım {
            get {
                return ResourceManager.GetString("Yorumlarım", resourceCulture);
            }
        }
    }
}
